### ISSUE TITLE
Allow mapping Serverless parameters to ServiceCatalog templates

### ISSUE THREAD

**Issue by jsmey** [godaddy/serverless-aws-servicecatalog#7]
Allow users to map the params in serverless.yml to an existing SC lambda template. This would eliminate the need to create a custom Serverless Lambda product.

I was thinking something like this in serverless.yml:

```
provider:
  stage: dev 
  SCstageParameterName: lambdaStage
```

**Comment by msluther** [comment]
@jsmey I was going to take a look at this issue, since I need it for something I was trying to do.

I was thinking something a bit more generic could work:

```
provider:
  scProductMapping:
    stage: MyCustomLambdaStageName
    runtime: MyCustomLambdaRuntimeName
    vpcSubnetIds: MyCustomVpcIdsNaming
```
