### ISSUE TITLE
Handle VPC option

### ISSUE THREAD

**Issue by jsmey** [godaddy/serverless-aws-servicecatalog#8]
Handle the optional VPC params form serverless.yml

```
 vpc: # Optional VPC. But if you use VPC then both subproperties (securityGroupIds and subnetIds) are required
    securityGroupIds:
      - securityGroupId1
      - securityGroupId2
    subnetIds:
      - subnetId1
      - subnetId2

```
